language: python
sudo: required
services:
  - docker
env:
  matrix:
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.12
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.12
cache:
  directories:
  - /home/travis/.tfsnippet
  - /home/travis/.keras
install:
  - docker pull "haowenxu/travis-tensorflow-docker:py${PYTHON_VERSION}tf${TENSORFLOW_VERSION}"
script:
  - docker run
      -v "$(pwd)":"$(pwd)"
      -v "/home/travis/.tfsnippet":"/root/.tfsnippet"
      -v "/home/travis/.keras":"/root/.keras"
      -w "$(pwd)"
      -e TRAVIS="${TRAVIS}"
      -e TRAVIS_JOB_ID="${TRAVIS_JOB_ID}"
      -e TRAVIS_BRANCH="${TRAVIS_BRANCH}"
      -e RUN_EXAMPLES_TEST_CASE=1
      "haowenxu/travis-tensorflow-docker:py${PYTHON_VERSION}tf${TENSORFLOW_VERSION}"
      bash -c "apt-get -y update && apt-get -y install unrar &&
        pip install . && pip install -r requirements-dev.txt &&
        mkdir -p /root/.config/matplotlib && echo 'backend : Agg' > /root/.config/matplotlib/matplotlibrc &&
        coverage run -m py.test && coveralls"
