language: python
sudo: required
services:
  - docker
env:
  matrix:
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.12
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.12
  - CORE_TESTS_ONLY=1
cache:
  directories:
  - /home/travis/.tfsnippet
  - /home/travis/.keras
script:
  - bash scripts/travis-run-tests.sh
